server:
  port: 9001

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.200:3306/pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    read-only: false
    #客户端等待连接池连接的最大毫秒数
    connection-timeout: 60000
    #允许连接在连接池中空闲的最长时间(以毫秒为单位)
    idle-timeout: 60000
    #连接将被测试活动的最大时间量
    validation-timeout: 3000
    #池中连接关闭后的最长生命周期
    max-lifetime: 60000
    #最大池大小
    maximum-pool-size: 60
    #连接池中维护的最小空闲连接数
    minimum-idle: 10
    #从池返回的连接的默认自动提交行为。默认值为true
    auto-commit: true
    #如果您的驱动程序支持JDBC4，我们强烈建议您不要设置此属性
    connection-test-query: SELECT 1
    #自定义连接池名称
    pool-name: MyHikariCP
  application:
    name: product
mybatis-plus:
  mapper-locations: classpath:mapper/product/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.jerry.gulimall.product: debug

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10


